name: OpenStack Workflow
on: push
jobs:
  openstack:
    runs-on: small
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Install OpenStack SDK
        run: | 
          python3 -m venv venv
          source venv/bin/activate
          pip install openstacksdk

      - name: Connect to OpenStack Cloud and List servers
        run: |
           cd python-openstack && source admin-openrc.sh
           python connect.py




      